version: '3.8'

services:
  traefik:
    image: "traefik:2.5.6"
    command: uvicorn main:app --host 0.0.0.0
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.app.rule=Host(`127.0.0.1`)"
      - "traefik.http.services.app.loadbalancer.server.port=8000"
    depends_on:
      - mysql
    environment:
      - DATABASE_URL=mysql+pymysql://root:123456@mysql:3306/trading_api

  mysql:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: 123456
      MYSQL_DATABASE: trading_api
      MYSQL_USER: root
      MYSQL_PASSWORD: 123456

networks:
  traefik:
    external: true

